# Generated by Django 4.2.8 on 2024-03-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_users_portalusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalusers',
            name='details',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
