# Generated by Django 4.2.8 on 2024-03-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_practice_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice_data',
            old_name='staff_id',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='practice_data',
            name='report_details',
        ),
        migrations.AddField(
            model_name='practice_data',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='practice_data',
            name='password_two',
            field=models.CharField(default='', max_length=10),
        ),
    ]
