# Generated by Django 5.0.4 on 2024-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_staff_id_practice_data_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
