# Generated by Django 5.0.4 on 2024-04-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_login_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_data',
            name='first_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='practice_data',
            name='last_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
